name: Check Codebase Formatting

on:
  pull_request:
    paths-ignore:
      - 'onomondo-uicc/**'
      - 'onomondo-uicc'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          FILES=$(find onomondo -name "*.c" -o -name "*.h" \
            | grep -v "onomondo-uicc/")
          clang-format --dry-run -Werror $FILES
